### ISSUE TITLE
api: empty _files field added in deposit but not in record

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio-deposit#107]
**Problem:**
When publishing a deposit for the first time. If the deposit has no files, it will still get an `_files` field added automatically and this field won't be added in the published record.

**Why this happens:**
`Deposit._publish_new` calls `Deposit. _process_files` which calls `self.files` which calls `invenio_records_files. FilesIterator` which [modifies the deposit itself by adding an `_files` field](https://github.com/inveniosoftware/invenio-records-files/blob/master/invenio_records_files/api.py#L108).
As [`Deposit._publish_new` had already made a copy of the deposit data](https://github.com/inveniosoftware/invenio-deposit/blob/master/invenio_deposit/api.py#L278), this new field is not added to the published record.

The impact is low but this is still a discrepancy as the published record should be an exact copy of the deposit when published.

Now the question is:
- do we remove the creation of the `_files` field from `self.files`? This in my opinion is the best design as an iterator should not modify anything. (This is similar to invenio-records-files/issues#21 where a getter creates the bucket)
- or do we add by default an empty `_files` field to the published record `data`? Simpler solution but kind of ugly as one has to dig in invenio-records-files to understand why it is needed. This might create bugs later when code is refactored (as it always is one day or the other).

**Comment by nharraud** [comment]
related to invenio-deposit/issues#95 and invenio-records-files/issues#23

**Comment by jirikuncar** [comment]
@nharraud we can try to update the `records['_files']` lazily in Invenio-Records-Files.

**Comment by nharraud** [comment]
Would then `dumps` just initialize `_files` to an empty list if there are not files, or would it be used to update the list in the `_files` field [instead of doing it in `Deposit._process_files`](https://github.com/inveniosoftware/invenio-deposit/blob/master/invenio_deposit/api.py#L253)?
