### ISSUE TITLE
deposit: multiple deposits per site

### ISSUE THREAD

**Issue by egabancho** [inveniosoftware/invenio-deposit#108]
Given the current configuration options for a deposit is not possible to have several/different deposit in one site. 

I think options like `DEPOSIT_DEFAULT_SCHEMAFORM` or `DEPOSIT_DEFAULT_JSONSCHEMA` should go together with the rest of the deposit configuration inside `DEPOSIT_REST_ENDPOINTS`.

I am not sure about other things, like templates.

**Comment by hachreak** [comment]
I think this [issue](https://github.com/inveniosoftware/invenio-records-rest/issues/101) is connected.
