### ISSUE TITLE
deposit: index record after being published

### ISSUE THREAD

**Issue by annatrz** [inveniosoftware/invenio-deposit#141]
After record being published, only deposit one is indexed. Would be nice to index also corresponding record under records-\* index.

**Comment by jirikuncar** [comment]
@annatrz 👍  just make sure that it is possible to turn off the automatic indexing for records.

**Comment by lnielsen** [comment]
@annatrz I think this is already the case - see [comment](https://github.com/inveniosoftware/invenio-deposit/pull/159#issuecomment-273797711) on #159

**Comment by lnielsen** [comment]
Closing as record is already being indexed on publish.
