### ISSUE TITLE
views: SSE integration

### ISSUE THREAD

**Issue by omelkonian** [inveniosoftware/invenio-deposit#144]
Add the ability to publish SSE events, which correspond to a particular deposit.

One possible solution is to register an endpoint to each deposit (i.e. `/deposits/<depid>/sse`), where a GET request would return an established connection with an SSE channel (having the same name as the deposit URL). Therefore, all handling of access rights concerning the SSE subscriptions will be provided by the `read_permission_factory` on the deposit.

**Comment by jirikuncar** [comment]
What about creating simple Invenio-Deposit-SSE extension that just iterates over the keys in `DEPOSIT_REST_ENDPOINTS`? It might be easier to keep it in sync with development of Invenio/Flask-SSE.

**Comment by omelkonian** [comment]
@jirikuncar The only problem with this approach is the duplicated code for setting up the blueprint (i.e. options, ctx, etc...). But I agree it is nice and clean to have everything in one place, therefore if you think this trade-off is acceptable, I will go with that.

**Comment by jirikuncar** [comment]
You don't need anything else then the endpoint prefix and pid_type. Moreover since it's SSE you are always going to return one type of response.

**Comment by omelkonian** [comment]
@jirikuncar Some considerations:

1. Should the new extension subclass `InvenioDepositRest`? After all, it adds a new REST endpoint.
2. Should it define a new blueprint or extend the `invenio_deposit_rest` one?
3. Apart from the `url_prefix`(why do I need this?) and `pid_type`, isn't it necessary to extract the `search_class`, `record_class` and `item_route` options from `DEPOSIT_REST_ENDPOINTS`?

**Comment by jirikuncar** [comment]
ad 1. No subclassing is necessary - `InvenioDepositSEE` which registers endpoints.
ad 2. Start with a new blueprint.
ad 3. You could even register everything under one endpoint with default argument providing key to `DEPOSIT_REST_ENDPOINTS`. You don't need `search_class` or `record_class` since you rely on `item_route`, which I forgot in previous comment.

**Comment by egabancho** [comment]
I think what @jirikuncar proposed [before] (https://github.com/inveniosoftware/invenio-deposit/issues/144#issuecomment-256664844) was creating a new package rather that adding it to deposit.

I think this is might be a bit of an overkill, what about doing something similar to [invenio-query-parser](https://github.com/inveniosoftware/invenio-query-parser) where we have a contrib folder with the different walkers? 
Meaning moving the code for the integration to `invenio-sse/contrib/deposit.py` WDYT?

**Comment by lnielsen** [comment]
IMHO it's best to either create a new package or go with the contrib in Invenio-SSE. If we add SSE support directly in Invenio-Deposit I'm afraid it creates precedences for other types of integration and we will end up with a package that does too many things and thus will have too high flux of changes going into it.

**Comment by omelkonian** [comment]
We decided to go with the `invenio/sse/contrib/...` approach.
