### ISSUE TITLE
api: record merging

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-deposit#61]
Add support in deposit record API for merging changes into record. The merging 
deals with the following situation:

1. Deposit (record v1) fetches record (record v1)
2. Deposit is updated (deposit v2 )
3. Record is updated (record v2)
4. Deposit is published (conflict!)

Since the record was updated after the it was loaded into the deposit, the 
deposit will be missing the updates from record v2.

Basic algorithm: 
- Patch from diff of deposit v2 against record v1 (i.e. which changes did the user make)
- Try to apply patch on record v2. If unsuccesful,  bail out (i.e. let user resovle conflicts).

Implementation:

- Merging should be plugged [here](https://github.com/inveniosoftware/invenio-deposit/blob/master/invenio_deposit/api.py#L214-L222)
- Implement algorithm in [``merge_with_published()``](https://github.com/inveniosoftware/invenio-deposit/blob/master/invenio_deposit/api.py#L133)
- [Invenio 2.0 version](https://github.com/inveniosoftware/invenio/blob/maint-2.0/invenio/modules/deposit/tasks.py#L258-L342) of same issue.

**Comment by kaplun** [comment]
@lnielsen you might be interested into the https://github.com/inspirehep/json-merger (demo at: http://merger.inspirehep.net/)
