### ISSUE TITLE
bug: remove "_deposit" before publishing

### ISSUE THREAD

**Issue by krzysztof** [inveniosoftware/invenio-deposit#67]
Deposit-specific information (``"_deposit": {...}``) should be removed from the JSON before those two steps:

https://github.com/inveniosoftware/invenio-deposit/blob/master/invenio_deposit/api.py#L213
https://github.com/inveniosoftware/invenio-deposit/blob/master/invenio_deposit/api.py#L221

**Comment by jirikuncar** [comment]
They should not, otherwise we lose the connection to deposit from record.
