### ISSUE TITLE
release: can we release a first alpha?

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio-deposit#83]
I just saw that there is no alpha released of invenio-deposit. Would it be possible to release one so that we can install B2Share with pip install without using the devel requirements?

I can make the PR if it is ok.

Thanks.

**Comment by lnielsen** [comment]
Done

**Comment by nharraud** [comment]
Thanks again @lnielsen. However it seems that pypi didn't get updated. https://pypi.python.org/pypi/invenio-deposit/1.0.0a1 => 404

**Comment by lnielsen** [comment]
Ups, fixed.
