### ISSUE TITLE
errors: exception InvalidOperationError not correctly handled by Flask

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio-deposit#91]
**Problem**

Because of this [change](https://github.com/inveniosoftware/invenio-files-rest/commit/023762ea621ae9e3dfe549d3b9fc0823d0e709c2#diff-dacc794350f23b3b0e02fd572a407601R32) now all files exceptions are subclasses of RESTException.

 `RESTException` [are managed](https://github.com/inveniosoftware/invenio-rest/blob/6f08ee8949745ca90dfc6637e09a3ac1e76c63c3/invenio_rest/views.py#L39) in a different way from invenio-rest `create_api_errorhandler()`.

Because of `InvalidOperationError` doesn't have a specific `code` set on the class, it inherits `500` from `FilesException`.
It means that is raised the 500 error instead of the 403 [set here](https://github.com/inveniosoftware/invenio-deposit/blob/master/invenio_deposit/views/rest.py#L67).

**Solutions**

Which solution make more sense in this case?

1. Set a default code `403` for the exception [InvalidOperationError](https://github.com/inveniosoftware/invenio-files-rest/blob/master/invenio_files_rest/errors.py#L49)

2. Modify the [create_api_errorhandler()](https://github.com/inveniosoftware/invenio-rest/blob/6f08ee8949745ca90dfc6637e09a3ac1e76c63c3/invenio_rest/views.py#L39) to force the status code if `'status' in kwargs`? (as done for `HTTPException`)

--------------------------------------------
ping @lnielsen @jirikuncar

**Comment by jirikuncar** [comment]
IMHO we should go for `InvalidOperationError.code = 403`
